# Generated by Django 3.1.2 on 2020-11-01 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sdc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseLevelHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('glucose_level', models.FloatField()),
            ],
            options={
                'db_table': 'patient_history',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('scheduled_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'meal_plan',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_time', models.DateTimeField()),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_to_med_sch', to='sdc.medication')),
            ],
            options={
                'db_table': 'medication_schedule',
                'ordering': ('-created_at',),
            },
        ),
    ]
