# Generated by Django 3.1.4 on 2021-01-07 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sdc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_to_med_sch', to='sdc.medication'),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_to_med_sch', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_to_meal_plan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='glucoselevelhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_to_pat_hist', to=settings.AUTH_USER_MODEL),
        ),
    ]
