# Generated by Django 3.1.2 on 2020-11-03 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('sdc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationschedule',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_to_med_sch', to='sdc.medication'),
        ),
    ]
